name: Setup Elixir
inputs:
  elixir-version:
    required: false
    type: string
    default: "1.17.1"
  otp-version:
    required: false
    type: string
    default: "27.0"
runs:
  using: "composite"
  steps:
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }
    - name: Get deps cache
      uses: actions/cache@v2
      with:
        path: deps/
        key: deps-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          deps-${{ inputs.cache-key }}-${{ runner.os }}-
    - name: Get build cache
      uses: actions/cache@v2
      id: build-cache
      with:
        path: _build/${{env.MIX_ENV}}/
        key: build-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}-${{ env.MIX_ENV }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          build-${{ runner.os }}-${{ inputs.otp-version }}-${{ inputs.elixir-version }}-${{ env.MIX_ENV }}-
    - name: Dependencies
      run: |
        mix deps.get
        mix deps.compile