name: Setup Elixir
inputs:
  elixir-version:
    required: true
    type: string
  otp-version:
    required: true
    type: string
runs:
  using: "composite"
  steps:
    - name: Setup elixir
      uses: erlef/setup-beam@v1
      with:
        elixir-version: ${{ inputs.elixir-version }}
        otp-version: ${{ inputs.otp-version }}

    - name: Dependencies cache
      uses: actions/cache@v4
      with:
        path: deps/
        key: deps-${{ runner.os }}-${{ hashFiles('**/mix.lock') }}
        restore-keys: |
          deps-${{ runner.os }}-

    - name: Install Dependencies
      run: |
        mix deps.get
        mix deps.compile
      shell: sh
