name: CI

on: [push, pull_request]

jobs:
  all:
    runs-on: ubuntu-latest
    continue-on-error: true

    steps:
      - uses: actions/checkout@v4.1.7
      - name: Setup Erlang/OTP, Elixir
        uses: erlef/setup-beam@v1.17.5
        with:
          elixir-version: 1.17.1
          otp-version: 27.0
      - name: Get dependencies cache
        uses: actions/cache@v4.0.2
        id: mix-cache
        with:
          path: deps
          key: mix-cache-key
      - name: Get dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: mix deps.get
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run credo
        run: mix credo --strict
      - name: Get PLT cache
        uses: actions/cache@v4.0.2
        id: plt-cache
        with:
          path: priv/plts
          key: plt-cache-key
      - name: Create PLTs
        if: steps.plt-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix dialyzer --plt
      - name: Run dialyzer
        run: mix dialyzer --no-check --halt-exit-status
  
