name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup Elixir
        uses: ./github/actions/elixir-setup
      
      - name: Compile application
        run: mix compile --all-warnings --warnings-as-errors
