name: Dialyzer

on: [push, pull_request]

jobs:
  dialyzer:
    name: Dialyzer
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Elixir
        uses: ./.github/actions/elixir-setup

      # update this when you change the versions in elixir-setup
      - name: Restore PLT cache
        uses: actions/cache@v2
        id: plt_cache
        with:
          key: ${{ runner.os }}-1.17.1-27.0-plt
          restore-keys: ${{ runner.os }}-1.17.1-27.0-plt
          path: priv/plts

      - name: Create PLTs
        if: steps.plt_cache.outputs.cache-hit != 'true'
        run: mix dialyzer --plt

      - name: Run Dialyzer
        run: mix dialyzer