name: Formatting, Credo, unused deps

on: [push, pull_request]

jobs:
  others:
    name: Formatting, Credo, unused deps
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Elixir
        uses: ./.github/actions/elixir-setup
      
      - name: Check for unused deps
        run: mix deps.unlock --check-unused
      
      - name: Check code formatting
        run: mix format --check-formatted
        if: always()
    
      - name: Run Credo
        run: mix credo --strict
        if: always()